// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"
)

type User struct {
	ID        string         `json:"id"`
	Email     string         `json:"email"`
	Name      sql.NullString `json:"name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	GoogleID  string         `json:"google_id"`
	IsActive  int64          `json:"is_active"`
	CreatedAt time.Time      `json:"created_at"`
	UpatedAt  interface{}    `json:"upated_at"`
}
