// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, google_id, email, name, avatar_url)
VALUES (?, ?, ?, ?, ?)
RETURNING id, email, name, avatar_url, google_id, is_active, created_at, upated_at
`

type CreateUserParams struct {
	ID        string         `json:"id"`
	GoogleID  string         `json:"google_id"`
	Email     string         `json:"email"`
	Name      sql.NullString `json:"name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpatedAt,
	)
	return i, err
}

const getUserByGoogleId = `-- name: GetUserByGoogleId :one
SELECT id, email, name, avatar_url, google_id, is_active, created_at, upated_at FROM users
WHERE google_id = ? LIMIT 1
`

func (q *Queries) GetUserByGoogleId(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleId, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.GoogleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpatedAt,
	)
	return i, err
}
